### ISSUE TITLE
Modifier does not work

### ISSUE THREAD

**Issue by umiaki** [valentine195/obsidian-initiative-tracker#11]
I have a player saved. In settings, I can see mod + 3 but the roll in the toolbar always says +0 (hover over initiative result).(I have the modifier stored in the header of player note as modifier: 3.
I'm not really sure where to set the %mod for creatures? But default creatures (Ancient Black Dragon) has +0 as well. I would assume it should have +dex mod (+2)?

**Comment by valentine195** [comment]
Is this still an issue?

Both players and monsters show their modifiers correctly for me.

**Comment by umiaki** [comment]
Updated all plugins and obsidian, but I still see only +0 in the initiative.
So what am I doing wrong?

I have a note with header (it's first thing in there):

---
hp: 17
ac: 15
modifier: 3
---

I then added a new player in settings using this note - all the fields from the note are loaded and player is saved.
The mod formula is the default 1d20 + %mod%

I create an encounter:

```encounter
name: What's for breakfast
players: true
creatures:
 - 2: Small Reef Shark
```

And when starting it, it does not work - shows X + 0 for everyone.

And I can see 3 monsters synced from Statblock but they are not listed in Initiative settings. Not sure where to put initiative modifier in the creature statblock definition either.

**Comment by valentine195** [comment]
Okay I will look into this. Thank you. Sorry it’s taking so long!

**Comment by umiaki** [comment]
No worries, thank a lot for creating this plugin, it's awesome!

**Comment by valentine195** [comment]
If you wouldn’t mind, could you take a look at the data file for the plugin and see if the modifier is in there for the players correctly?

it will be located in `<vault>/.obsidian/obsidian-initiative-tracker/data.json`

**Comment by umiaki** [comment]
I will once I get home, don't know where to find it on androud. But since it is showing correctly in settings as stored player, I would assume it is ok in there?

**Comment by valentine195** [comment]
Yes, probably is. Thanks though!

**Comment by umiaki** [comment]
{
  "players": [
    {
      "note": "Steboup",
      "name": "Steboup",
      "ac": 15,
      "hp": 17,
      "modifier": 3,
      "player": true
    }
  ],
  "homebrew": [],
  "version": null,
  "canUseDiceRoll": false,
  "initiative": "1d20 + %mod%",
  "sync": true,
  "leafletIntegration": false,
  "playerMarker": "default",
  "monsterMarker": "default",
  "state": {
    "creatures": [],
    "state": false,
    "current": null,
    "name": null
  }
}

**Comment by joellemm** [comment]
I just installed the plugin today, and I'm having this issue as well. Got the following encounter:

```encounter
name: Fight
creatures:
- 3: Salamander, 60, 12, 20
```

The initiative isn't being added anywhere. When I hover over Salamander in the note preview I see HP and AC but no modifier, and in the Encounter panel, the initiative rolls say +0 and are all <20 (so clearly the +20 modifier isn't being added).

Bug aside, I appreciate your work on the plugin, this looks great!

**Comment by umiaki** [comment]
btw, is there a way to modify only initiative? Like:
- 1: Goblin, X, X, 2
so use Goblin with his stats just add to initiative?
Also, is the default modifier calculated from the dex from the statblock?

**Comment by valentine195** [comment]
If you leave a value blank, it will use the default value for the creature (if the creature is in your Bestiary in settings).

> Also, is the default modifier calculated from the dex from the statblock?

Yes, it is calculated from the dexterity of creatures in the SRD. If you add a new creature, it will come from the value you put in the field.

I will work on this ASAP - I think it might be an issue from launching from encounters in notes. Does it happen if you add everything using the Add Creature button in the tracker view?

**Comment by joellemm** [comment]
> Does it happen if you add everything using the Add Creature button in the tracker view?

@valentine195 oh interesting, no it does not. Works correctly from the Add Creature button. Still learning the tool, I hadn't found that way of doing it yet.

**Comment by valentine195** [comment]
Thanks for letting me know! I believe I have identified the bug, will have a fix out in the next few days once I get a chance to work on it.

**Comment by valentine195** [comment]
This should work properly now in 3.1.1

Also, I just saw this question:

> And I can see 3 monsters synced from Statblock but they are not listed in Initiative settings. Not sure where to put initiative modifier in the creature statblock definition either.

These creatures will be in the settings for the 5e Statblock plugin. You can modify them there.

**Comment by umiaki** [comment]
Works nice, thanks a lot! :)
