### ISSUE TITLE
Is it possible to save the initiative tracker's current initiative across startups?

### ISSUE THREAD

**Issue by WychWitch** [valentine195/obsidian-initiative-tracker#12]
Hello! I run a play-by-post game with some friends over discord so some encounters can last over the course of a few days. I use the plugin for grabbing the initial order and keep track elsewhere, but I can't seem to find how to save it. Is it possible and I'm just blind? Or is this not a feature at this current time?

If it's the latter I can't request it enough, even if it does something as simple as saving and loading from a markdown or yaml file. Besides that issue I love this plugin and the ways it interacts with other dnd plugins available for obsidian!

**Comment by valentine195** [comment]
Not possible yet, but easily doable - will add ASAP! If not this weekend, definitely on Monday.

**Comment by WychWitch** [comment]
> 
> 
> Not possible yet, but easily doable - will add ASAP! If not this weekend, definitely on Monday.

!! Thank you SO much!! This will my workflow during encounters 200% easier you have no idea ;u;

**Comment by valentine195** [comment]
Hi, this should work in 3.1.0.

**Comment by WychWitch** [comment]
> 
> 
> Hi, this should work in 3.1.0.

HELLO THANK YOU SO MUCH FOR WORKING ON THIS SO QUICKLY!! However bizarrely it doesn't seem to work for me? I doublechecked that I was on 3.1.0 and even reinstalled just in case I wasn't. and whenever I close obsidian and reopen it doesn't work. I even pressed play on it just in case that was the issue.

It's possible another plugin might be interfering?? I'll try disabling everything and editing this reply.

For reference I'm using obsidian 0.12.15 on desktop, and the other related extensions installed are statblocks and leafletjs (though I have much more unrelated ones)

Also let me knwo if I should open a new issue!

**Comment by valentine195** [comment]
Hmm, no, it should just be the plugin. Possibly buggy!

I *did* make it only work if the encounter is *active*.

**Comment by valentine195** [comment]
Interesting though, because I just uninstalled and re-installed the plugin and it works. Hmm, could you open the developer console (ctrl-shift-i or cmd-alt-i on Mac) and let me know if there are any errors if you can see if you right-click the tracker and close it, then re-add it with the command?

**Comment by WychWitch** [comment]
OH I am getting errors, hold on

<details>
<summary> error when adding to encounter</summary>

```error
app.js:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at va.buildPopup (eval at <anonymous> (app.js:1), <anonymous>:2:1345944)
    at va.getPopup (eval at <anonymous> (app.js:1), <anonymous>:2:1345167)
    at va.open (eval at <anonymous> (app.js:1), <anonymous>:2:1343473)
    at qn.onShow (eval at <anonymous> (app.js:1), <anonymous>:2:1489495)
    at qn.show (eval at <anonymous> (app.js:1), <anonymous>:2:1354585)
    at qn.checkAndAddToMap (eval at <anonymous> (app.js:1), <anonymous>:2:1347722)
    at new Ba (eval at <anonymous> (app.js:1), <anonymous>:2:1350311)
    at new qn (eval at <anonymous> (app.js:1), <anonymous>:2:1487865)
    at Kn.addCreature (eval at <anonymous> (app.js:1), <anonymous>:2:1487423)
    at Fn.loadSavedData (eval at <anonymous> (app.js:1), <anonymous>:2:1484999)
```
</details>


<details>
<summary> error when re-opening the initiative tracker after closing</summary>

```error
app.js:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at va.buildPopup (eval at <anonymous> (app.js:1), <anonymous>:2:1345944)
    at va.getPopup (eval at <anonymous> (app.js:1), <anonymous>:2:1345167)
    at va.open (eval at <anonymous> (app.js:1), <anonymous>:2:1343473)
    at qn.onShow (eval at <anonymous> (app.js:1), <anonymous>:2:1489495)
    at qn.show (eval at <anonymous> (app.js:1), <anonymous>:2:1354585)
    at qn.checkAndAddToMap (eval at <anonymous> (app.js:1), <anonymous>:2:1347722)
    at new Ba (eval at <anonymous> (app.js:1), <anonymous>:2:1350311)
    at new qn (eval at <anonymous> (app.js:1), <anonymous>:2:1487865)
    at Kn.addCreature (eval at <anonymous> (app.js:1), <anonymous>:2:1487423)
    at Fn.loadSavedData (eval at <anonymous> (app.js:1), <anonymous>:2:1484999)
```
</details>

Closing the initiative tracker does not cause any errors.

Since it was complaining about rects, I figured it was an issue with the leaflet.js plugin, so I disabled the integration in the initiative tracker plugin and tried again, and it works!! ALMOST??

The initiative tracker only saves its creatures states if the initiative tracker itself is closed, not if the entire program is closed. Unless this is intended behavior??

Again, thank you so much for taking time out of your day to poke at this ;u;

**Comment by valentine195** [comment]
No worries! Thanks for digging into this. I’ll test this behavior out a little more. Sorry about that!

It *should* be saving when closing the app (as long as the encounter is active). I may just need to make it more robust. Will work on it Monday at the latest!

**Comment by WychWitch** [comment]
Don't mention it!! You're the one doing all the work all I did is check the error logs

Again, I appreciate you working on this so much!!

**Comment by valentine195** [comment]
Did you have the Leaflet map up when you were getting these errors?

**Comment by valentine195** [comment]
Can you check and see if this issue is resolved in 3.1.1?

**Comment by WychWitch** [comment]
> Did you have the Leaflet map up when you were getting these errors?

No I didn't! That was the weird thing... 

> Can you check and see if this issue is resolved in 3.1.1?

I just checked, both with initiative tracker's integration enabled and with it disabled and it works flawlessly!!! Again thank you so much for working on this feature ;;u;;

**Comment by valentine195** [comment]
> I just checked, both with initiative tracker's integration enabled and with it disabled and it works flawlessly!!! Again thank you so much for working on this feature ;;u;;

Great news :) I will close this issue now, but will keep trying to figure out where those errors are coming from. If you happen to notice them again, could you open a new issue?

Thank you!

**Comment by WychWitch** [comment]
I will!! I'll check in the inspector occasionally as I use it ^^
