### ISSUE TITLE
[Feature Request] Option to Hide Players in Encounter Block

### ISSUE THREAD

**Issue by SlRvb** [valentine195/obsidian-initiative-tracker#19]
Sometimes I only want to see the creatures in the encounter, so the players end up taking up a lot of vertical space that I don't really need to see.

Having an option for the encounter codeblock to hide the players from each or all would be great.

Maybe something like `hide: players` or `players: (hide) Name, Name`. This is mostly visual so I still want the players to load up once the encounter begins though.

````
```encounter
name: 2. Goblin Blind
hide: players
players:
- Althea Amasticia
- Salazar
- Amafrey
creatures:
- Goblin, 5
- Goblin, 4
```
````

````
```encounter
name: 2. Goblin Blind
players: (hide)
- Althea Amasticia
- Salazar
- Amafrey
creatures:
- Goblin, 5
- Goblin, 4
```
````

Results in:
![Obsidian_DC5amVulai](https://user-images.githubusercontent.com/54087190/145754944-bc5ccac1-52ee-4d06-957d-11a5dcaddacb.png)

**Comment by valentine195** [comment]
This will be in the next release with this syntax:

```md
hide: players
---
hide: creatures
---
hide:
 - creatures
 - players
 ```

**Comment by valentine195** [comment]
Implemented with v5+
