### ISSUE TITLE
Question for Initiative roll

### ISSUE THREAD

**Issue by mhofherr** [valentine195/obsidian-initiative-tracker#2]
Hi Jeremy,

FYI, I just tested this plugin on ipad pro 12.9 and my initial tests showed no problems so far.

I have the following questions for this plugin (all based on tests with Desktop version on Mac OS):
- I added "Homebrew"-monsters from my own Monster-files (in "Plugin options"). When I try to delete them by clicking on the trash bin, I get the message: "There was an error deleting the monster: Method not implemented". User error or bug?
- When adding a new creature with "Add Creature" in right pane, there seems to be no initiative modifier, but only an initiative field. This seems to not work as a modifier? When I add here a value of "10" and I re-roll initiative several times, I get values below 10.

And a general question: How exactly is initiative calculated (1d20+modifier?). Would it be possible to configure this via settings? I use Fantasy AGE, which uses 3d6 + modifier.

BTW: Thank you very much for your great plugins! I intend to use most of them (with the exception of 5e Statblocks, which is unfortunately too DND-specific for me).

Best,
Matthias

**Comment by valentine195** [comment]
Thanks for testing it on iPad! Hopefully the mobile beta opens soon so I can start testing on mobile as well.

> I added "Homebrew"-monsters from my own Monster-files (in "Plugin options"). When I try to delete them by clicking on the trash bin, I get the message: "There was an error deleting the monster: Method not implemented". User error or bug?

Whoops! I swear I added that - must still be on my dev machine 😅

> When adding a new creature with "Add Creature" in right pane, there seems to be no initiative modifier, but only an initiative field. This seems to not work as a modifier? When I add here a value of "10" and I re-roll initiative several times, I get values below 10.

Yeah this is basically just so you can enter an initiative immediately when adding a new monster, but I suppose there isn't a way to set modifiers outside of homebrew. Will add!

> And a general question: How exactly is initiative calculated (1d20+modifier?). Would it be possible to configure this via settings? I use Fantasy AGE, which uses 3d6 + modifier.

Correct, it is just 1d20. I can certainly open up support for other systems, just need to think of a clean way to do it.

> BTW: Thank you very much for your great plugins! I intend to use most of them (with the exception of 5e Statblocks, which is unfortunately too DND-specific for me).

You're very welcome! It would definitely be difficult to adapt the statblocks to other systems, but if it's an appearance thing, it would all be configurable in CSS 😁

**Comment by mhofherr** [comment]
Thank you very much, had immediately a first look :-)
Everything seems to work fine. One observation: when adding a homebrew-creature, the initial initiative-value seems to not consider the defined modifier. This is only upon first entry, after initiative-rerolls, everything works fine.

**Comment by mhofherr** [comment]
Sorry, based on further testing: The modifier for homebrew creatures seems not to be considered (neither initially nor on re-rolls).

**Comment by valentine195** [comment]
Can you tell me what initiative formula you entered so I can test?

**Comment by mhofherr** [comment]
Formula is: 3d6 + %mod%

**Comment by valentine195** [comment]
I believe this is fixed in 1.0.0.

By the way, the plugin was released into the community list. Please install it from there!

**Comment by mhofherr** [comment]
I installed the new version and had a look. I found two remaining issues, everything else worked fine:
- modifier from homebrew-creature is not used when adding it to an encounter (always is 0)
- when adding a creature for the first time to an encounter, initial initiative roll uses 1d20, even when I set "3d6" as basis. When using "re-roll initiative", everything works fine

**Comment by valentine195** [comment]
> modifier from homebrew-creature is not used when adding it to an encounter (always is 0)

Can you try this with a newly-created homebrew creature?

> when adding a creature for the first time to an encounter, initial initiative roll uses 1d20, even when I set "3d6" as basis. When using "re-roll initiative", everything works fine

Fixed in 1.0.1

**Comment by mhofherr** [comment]
> > modifier from homebrew-creature is not used when adding it to an encounter (always is 0)
> 
> Can you try this with a newly-created homebrew creature?

Tried with two different new creatures (values imported from YAML) and both had modifier 0 when adding. To be sure, tried with new creature without values from YAML => started with 0 as well

As regards initial initiative: Seems to still use 1d20 instead chosen initiative formula. I set it to "1d6 %mod%" for testing and still got 19 and 20 for initial initiative when adding.

Version: 1.0.1

**Comment by valentine195** [comment]
Hmm, bizarre. I'll have to do some more digging. 
![test](https://user-images.githubusercontent.com/38669521/125990720-30fb30f7-3f4a-44b3-b35d-5e3072478765.gif)

**Comment by mhofherr** [comment]
I tried exactly the same as you (name = test, added only "5" as modifier) and got new creature "test" with a 0-Modifier when adding to encounter. There must be something different between your setup and mine.

Please tell me if you want me to test something.

**Comment by mhofherr** [comment]
> Edit: `1d6 %mod%` is not valid - is it `1d6 + %mod%` ? If it can't parse the formula, it will fall back to 1d20.

Sorry, just a typo in my message above. I use: 1d6 + %mod%

**Comment by valentine195** [comment]
If you open the console (Control-Shift-i / Command+Option+i), are there any errors?

**Comment by mhofherr** [comment]
Opened console => deleted all homebrew => added new homebrew => added creature to new encounter => still modifier 0 and no error in console

**Comment by valentine195** [comment]
Okay, thanks for trying to debug. Obviously something is going wrong somewhere, just have to hunt it down. I may have to push an update with some logging enabled to see what's actually happening on your setup.

**Comment by mhofherr** [comment]
hm, tried the same setup on my ipad pro on Obsidian Mobile. Here it worked without problems. So it seems to be a local problem on my MAC OS-installation. <= sorry
will try to debug if it is either another plugin or if something different is broken ...

**Comment by valentine195** [comment]
Interesting. I would suggest 2 things:

1. Completely uninstall and reinstall the plugin. Could be an artifact from having it installed manually.
2. I believe there was an Electron upgrade recently. This requires a re-install of Obsidian (just have to download a new installer from the website, everything will copy over). Sometimes, having mis-matching Electron versions causes issues with the JavaScript and CSS engines.

**Comment by mhofherr** [comment]
Thanks, it actually was (1). Tested the different problems from before and everything works fine now. Sorry again ...

**Comment by valentine195** [comment]
No worries! Glad it worked :)
