### ISSUE TITLE
New Code Block Type - Single Line Option For Tables

### ISSUE THREAD

**Issue by Sklore** [valentine195/obsidian-initiative-tracker#22]
It would be handy if the code block for triggering an encounter could be written:
- in a single line
- so that it can be displayed in tables. 

**Use Case:** Random encounter tables often display lists of monsters to fight. Currently you need to make the encounter block beneath the table which then takes up a lot of screen space. If we could write it as a single line and then place that in a table cell it would clean up a lot of screen space. 

![image](https://user-images.githubusercontent.com/8046697/148667381-f84a5136-60d4-4d76-8f61-b5fcaf42e07d.png)

**Comment by valentine195** [comment]
I think this is closed with the `encounter-table` block processor and the new inline codeblock `encounter`.
