### ISSUE TITLE
Select a creature to view it here panel in sidebar wont disappear

### ISSUE THREAD

**Issue by allanmohr** [valentine195/obsidian-initiative-tracker#25]
Initiative Tracker v7.0

When clicking away from the initiative tracker  in a side panel and viewing another panel, the statblock viewer recently introducted w/ a recent Init Tracker update will not go away nor can you click on a "close" button.

**Comment by valentine195** [comment]
Is this still an issue? I could never recreate this.

Specifically, you right click the dragon icon of the stat block viewer.
