### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by lishid** [valentine195/obsidian-initiative-tracker#3]
Hi there, it seems that your plugin ID doesn't match the one that was submitted to the plugins repo:

"obsidian-initiative-tracker" vs "initiative-tracker"

https://github.com/valentine195/obsidian-initiative-tracker/blob/master/manifest.json#L2

This causes Obsidian to fail to install your plugin - let me know which side you want to get this changed.

**Comment by valentine195** [comment]
Ah, I updated this to remove the "Obsidian" - "initiative-tracker" please. Sorry.

**Comment by lishid** [comment]
Like this, right? https://github.com/obsidianmd/obsidian-releases/commit/f4fe38be64425a400e79ae0cbe9cefe2eb02992c

**Comment by valentine195** [comment]
I removed Obsidian from the name as well (that's the community guideline, right?) but yes. Thank you.

**Comment by lishid** [comment]
Sure, I can do that for you too - We're not picky with names hehe
