### ISSUE TITLE
Status input glitch

### ISSUE THREAD

**Issue by Chr9sG** [valentine195/obsidian-initiative-tracker#37]
If I "add status" then type something (i.e., not select one of the default choices) then click on a different window before closing the status input (i.e., hitting return) Initiative Tracker freezes. This happens even if I only hit the space bar and then click on a different window before returning to Initiative Tracker. 

I then have to close obsidian and then re-open it to get Initiative Tracker to work again - but then the encounter has reset, and I've lost all the changes.

**Comment by Chr9sG** [comment]
Just checked. A whole set of errors pop up. 

![image](https://user-images.githubusercontent.com/97812598/167275843-3cd22036-8b6a-42a3-aaa7-ed9a8a9bccdb.png)

**Comment by SondreElg** [comment]
This problem seems to be fixed in the latest release

**Comment by Chr9sG** [comment]
It isn't fixed but it is acting differently now. The plugin doesn't freeze any more, but the status won't actually display after you click off prior to entering. The net result is you still have to be careful to not click off the entry window prior to entering the condition unless you're selecting multiple entries (oddly enough). And, to get it to fully work again you have to close and reopen the plugin which unfortunately resets all the data if you forget to save the encounter prior to closing.

**Comment by Chr9sG** [comment]
Looks like the various changes have made this issue a moot point so I'm closing it.
