### ISSUE TITLE
Tracker doesn't get rendered

### ISSUE THREAD

**Issue by Hamath-Eltrael** [valentine195/obsidian-initiative-tracker#39]
Hello,

I just started using Obsidian and your initiative-tracker. For some time it worked and after a restart the code doesn't get rendered. It doesn't throw any errors like it does with wrong syntax.
I'm on MacOS

Code:
```
\```encounter
name: Drachennest
creatures: 
 - 1: Young White Dragon
 - 3: Ice Mephit
\```
```
_without the slashes_

### Code:
<img width="884" alt="Bildschirmfoto 2022-06-04 um 19 56 23" src="https://user-images.githubusercontent.com/60324384/172019750-1e477818-4429-45dc-8bc4-c204ef780cd6.png">

### Result:
<img width="884" alt="Bildschirmfoto 2022-06-04 um 19 56 56" src="https://user-images.githubusercontent.com/60324384/172019770-a8f25aae-7a2c-4eb7-b3d5-d8a3c939ae2c.png">

**Comment by Hamath-Eltrael** [comment]
Just found something out: There is a box you can make visible with your mouse. The Button you can kind of see only places you in edit mode
<img width="884" alt="Bildschirmfoto 2022-06-04 um 22 20 39" src="https://user-images.githubusercontent.com/60324384/172024423-ed4bf015-1273-44be-ace6-8572f03cf186.png">
.

**Comment by Chr9sG** [comment]
Not rendering for me either. I'm on a windows machine. I checked some earlier encounter blocks that I had created and they aren't rendering either.

I am getting this error

![image](https://user-images.githubusercontent.com/97812598/172030263-bef8489e-38b5-40ac-82c4-b9547d7cc1fb.png)

**Comment by Hamath-Eltrael** [comment]
@Chr9sG Where did you find those errors?

**Comment by valentine195** [comment]
Forgot to update here - this should be fixed if you update both initiative tracker and dice roller. 

You can find those in the developer console of obsidian. With obsidian open press ctrl/shift/i or cmd/alt/i (mac)

**Comment by Chr9sG** [comment]
@Hamath-Eltrael 

When you have an issue with a plugin type ctrl-shft-I

That opens the developers console which indicates what is happening in the execution of the code.

**Comment by Hamath-Eltrael** [comment]
Thanks man!
