### ISSUE TITLE
Condition Selection not visible on ipad

### ISSUE THREAD

**Issue by cenycal** [valentine195/obsidian-initiative-tracker#48]
When using the initiative tracker on an ipad I can select a creature and see the edit, add status, disable, remove options. But when I select "add status" nothing appears and I am unable to assign a status to the creature.

**Comment by SondreElg** [comment]
What version of Obsidian do you have installed, and did this problem appear recently?

**Comment by cenycal** [comment]
The most recent update resolved this issue
