### ISSUE TITLE
Encounter table XP and difficulty calculations not accounting for multiple instances of same creature

### ISSUE THREAD

**Issue by acowens** [valentine195/obsidian-initiative-tracker#50]
When an encounter is created in a note using `encounter-table`, the calculated XP and resulting difficulty do not appear to account for multiple instances of the same creature, and as a result an incorrect XP and difficulty are shown in the table view. The correct XP and difficulty are shown when the encounter is launched.

Example: an encounter with 5 bugbears (CR 1, 200 XP) should have a total XP of 2000 (1000 XP from the bugbears, multiplied by 2 for the number of opponents). For a party of 3 level 5 characters, this should be a Medium encounter. However, an encounter created using 
```
encounter-table
name: Five Bugbears
creatures:
  - 5: Bugbear
```

(with a default party of 3 level 5 characters) shows the encounter difficulty as Easy, and the hovertext for difficulty shows a total XP of 200, with an adjusted XP of 200. When the encounter is launched, the initiative tracker correctly shows the encounter difficulty as Medium, with a total XP of 1000 and an adjusted XP of 2000.

If the same encounter is created using
```
encounter
name: Five Bugbears
creatures:
  - 5: Bugbear
```
the correct difficulty and XP are displayed in the note.

Side note: thanks for a great set of plugins, these are incredibly useful!

**Comment by Hamath-Eltrael** [comment]
I have the same Problem, but I tried separating the Enemy's out into each their own line with then everyone the amount set to 1 so:
```
name: Five Bugbears
creatures:
 - 1: Bugbear
 - 1: Bugbear
 - 1: Bugbear
 - 1: Bugbear
 - 1: Bugbear
 ```
 but that does not fix the problem and still displays the XP as with OP.
