### ISSUE TITLE
Encounter Difficulty calculator in Note not calculating difficulty correctly

### ISSUE THREAD

**Issue by namtrah** [valentine195/obsidian-initiative-tracker#63]
When creating an encounter, either as table or single one, the encounter difficulty (when turned on) isn't calculating correctly inside of the note. Only when actually starting an encounter does it correctly show on the right hand side bar.

```Markdown
```encounter-table
name: Night at the Inn
players:
 - Player Wizard
 - Player Barbarian
 - Player Druid
 - Player Fighter
creatures:
 - 4: Giant Rat
---
name: In the forest
players:
 - Player Wizard
 - Player Barbarian
 - Player Druid
 - Player Fighter
creatures:
- 2: Werewolf
```

Example: https://cdn.discordapp.com/attachments/932707309195493416/1012774210009047192/unknown.png

**Comment by namtrah** [comment]
Then it must be a regression. I am on the latest BRAT update even. It doesn't work.

**Comment by valentine195** [comment]
This should be improved in v8.0.9
