### ISSUE TITLE
Difficulty calculations not working in read view

### ISSUE THREAD

**Issue by andrgram** [valentine195/obsidian-initiative-tracker#67]
The difficulty calculations currently only count monsters only once per monster type in the markdown read view. In the initiative tracker window, the calculations work as expected, with modifiers according to how many monsters are in combat, but the markdown read view will display fighting 500 cultists to be an easy encounter with 12500 xp and an x1 modifier.
![image](https://user-images.githubusercontent.com/54682731/189357854-2dcb8ac8-8ae7-48cf-bb57-9cff75452f7a.png)
![image](https://user-images.githubusercontent.com/54682731/189358177-795fc5b7-dfed-4810-a4b2-eb6d8afc6a3f.png)

**Comment by valentine195** [comment]
This should be improved in v8.0.9, but I will probably end up rewriting how this works.
