### ISSUE TITLE
[Feature Request] Please add an option to change the text size on the player view window.

### ISSUE THREAD

**Issue by dwightdurmon** [valentine195/obsidian-initiative-tracker#90]
**Is your feature request related to a problem? Please describe.**

Depending on the size of the monitor, the information shown in the Player View can be harder to read.

**Describe the solution you'd like**

It would be nice to be able to either set the font size or be able to zoom in and out to scale the font in the Player View window.

**Describe alternatives you've considered**

Currently the only alternative seems to be to use a bigger monitor.  Zooming in and out on the Player View does not work. Setting the font size via the Settings -> Appearance -> Font Size does not appear to change the size of the font in the Player view.

**Additional context**

This should be considered a quality of life request and definitely not critical as it is not a functionality breaking bug.

**Comment by valentine195** [comment]
Zooming doesn’t work? Weird!

Does Ctrl-+ work?

**Comment by dwightdurmon** [comment]
It does!  I apologize... I just started using Obsidian today and missed the Ctrl-+.  Thanks so much!

**Comment by valentine195** [comment]
No problem! Ctrl- - goes the other way and Ctrl-0 resets it.
